min_version = "2026.7.0"

[settings]
dotfiles.root = "~/.dotfiles"
dotfiles.default_mode = "symlink"

[bootstrap.hooks]
pre-packages = [
  "scripts/setup-repos.sh",
  "sudo dnf upgrade -y"
]
post-packages = [
  "mise run bootstrap"
]

[bootstrap.hooks.final]
run = "echo \"bootstrap.hooks.final\""
#run = "gh auth status || gh auth login"

[bootstrap.packages]
"dnf:@development-tools" = "latest"
"dnf:@c-development" = "latest"
"dnf:curl" = "latest"
"dnf:wget" = "latest"
"dnf:git" = "latest"
"dnf:zsh" = "latest"
"dnf:vim" = "latest"
"dnf:tmux" = "latest"
"dnf:htop" = "latest"
"dnf:btop" = "latest"
"dnf:jq" = "latest"
"dnf:unzip" = "latest"
"dnf:fastfetch" = "latest"
"dnf:ripgrep" = "latest"
"dnf:fd-find" = "latest"
"dnf:bat" = "latest"
"dnf:fzf" = "latest"
"dnf:tree" = "latest"
"dnf:util-linux-user" = "latest"
"dnf:net-tools" = "latest"
"dnf:ca-certificates" = "latest"
"dnf:gnupg2" = "latest"
"dnf:age" = "latest"
"dnf:pass" = "latest"
"dnf:gopass" = "latest"

[bootstrap.repos]
"~/.dotfiles" = { url = "git@github.com:snwiem/dotfiles.git", ref = "main" }

[bootstrap.user]
login_shell = "/usr/bin/zsh"

[tools]
"eza" = "latest"
"zoxide" = "latest"
"neovim" = "latest"
"starship" = "latest"
"herdr" = "latest"
"pi" = "latest"
gh = "latest"

[dotfiles]
"~/.config/mise/config.toml" = "mise.toml"
"~/.bashrc" = "config/bash/bashrc"
"~/.bash_profile" = "config/bash/bash_profile"
"~/.bash_logout" = "config/bash/bash_logout"
"~/.zshrc" = "config/zsh/zshrc"
"~/.zprofile" = "config/zsh/zprofile"
"~/.config/git/config" = "config/git/config"
"~/.config/nvim" = "config/nvim"

[tasks.bootstrap]



