[bootstrap.packages]
"dnf:git" = "latest"
"dnf:zsh" = "latest"
"dnf:util-linux-user" = "latest"

[bootstrap.user]
login_shell = "/usr/bin/zsh"

# 2. Deine Dotfiles automatisch an die richtige Stelle linken
[dotfiles]
# Verlinkt deine .zshrc aus dem Repo nach ~/.zshrc
#"~/.zshrc" = "./dotfiles/.zshrc"
"~/.config/git/config" = "{{config.root}}/../git/config"

# 3. Globale Entwicklungs-Tools, die mise verwalten soll
[tools]
